name: Deploy Jar to Prod
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Jar
        uses: tyrrrz/action-http-request@a675917a18329fee80af4e04f970546ac44df8ad
        with:
          url: ${{secrets.JAR_DEPLOY_URL}}
          method: POST
          headers: |
            Content-Type: application/json
            Accept: "application/json
            Authorization: Basic ${{secrets.BOOMI_AUTH_STRING}}
          body: |
            {
              "environmentId": "${{secrets.TF_VAR_BOOMI_ENVIRONMENT_ID}}",
              "packageId": "${{secrets.JAR_PACKAGE_ID}}"}
            }
          retry-count: 3
          retry-delay: 500
