name: Deploy Jar to Prod
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Jar
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.JAR_DEPLOY_URL}}
          method: POST
          username: ${{secrets.TF_VAR_BOOMI_USERNAME}}
          password: ${{secrets.TF_VAR_BOOMI_AUTH_TOKEN}}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"environmentId": "${{secrets.TF_VAR_BOOMI_ENVIRONMENT_ID}}", "packageId": "${{secrets.JAR_PACKAGE_ID}}"}'
